apiVersion: v1
kind: Namespace
metadata: # kpt-merge: /istio-ingress
  name: istio-ingress
  annotations:
    internal.kpt.dev/upstream-identifier: '|Namespace|default|istio-ingress'
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata: # kpt-merge: istio-ingress/istio-ingress
  name: istio-ingress
  namespace: istio-ingress
  annotations:
    internal.kpt.dev/upstream-identifier: 'helm.toolkit.fluxcd.io|HelmRelease|istio-ingress|istio-ingress'
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: gateway
      version: '1.20.*'
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: istio-system
      interval: 5m
  releaseName: istio-ingress
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: false
  driftDetection:
    mode: enabled
    ignore:
    # ignore Horizontal Pod Autoscaling
    - paths: ["/spec/replicas"]
      target:
        kind: Deployment
  values:
    service:
      # Static IP created by terraform
      loadBalancerIP: # PATCH ME
