apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata: # kpt-merge: istio-system/istiod
  name: istiod
  namespace: istio-system
  annotations:
    internal.kpt.dev/upstream-identifier: 'helm.toolkit.fluxcd.io|HelmRelease|istio-system|istiod'
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: istiod
      version: '1.20.*'
      sourceRef:
        kind: HelmRepository
        name: istio
      interval: 5m
  releaseName: istiod
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: false
  driftDetection:
    mode: enabled
    ignore:
    # ignore Horizontal Pod Autoscaling
    - paths: ["/spec/replicas"]
      target:
        kind: Deployment
  values:
