apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
patches:
- patch: |
    apiVersion: helm.toolkit.fluxcd.io/v2
    kind: HelmRelease
    metadata:
      name: podinfo
      namespace: default
    spec:
      kubeConfig:
        secretRef:
          name: ${TYPE}-${REGION}/cluster-kubeconfig
      values:
        replicaCount: 1
