apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: arbitrary
resources:
- ../base
patches:
- patch: |
    apiVersion: helm.toolkit.fluxcd.io/v2
    kind: HelmRelease
    metadata:
      name: podinfo
      namespace: default 
    spec:
#      valuesFrom:
#      - chartFileRef:
#          path: values-tenant.yaml
