apiVersion: v1
kind: Namespace
metadata:
  name: istio-ingress
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: istio-ingress
  namespace: istio-ingress
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: gateway
      version: '1.20.*'
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: istio-system
      interval: 5m
  releaseName: istio-ingress
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: false
  driftDetection:
    mode: enabled
    ignore:
    # ignore Horizontal Pod Autoscaling
    - paths: ["/spec/replicas"]
      target:
        kind: Deployment
  values:
    service:
      # Static IP created by terraform
      loadBalancerIP: # PATCH ME
