apiVersion: v1
kind: Namespace
metadata:
  name: tenant-12345
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tenant-12345
  namespace: tenant-12345
spec:
  interval: 1h
  retryInterval: 3m
  timeout: 5m
  prune: true
  wait: true
  path: ./deploy/tenant
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  postBuild:
    substitute:
      REGION: las1
      TYPE: tenant
