apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: istio
  namespace: istio-system
spec:
  interval: 5m
  url: https://istio-release.storage.googleapis.com/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: istio-base
  namespace: istio-system
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: base
      version: '1.20.*'
      sourceRef:
        kind: HelmRepository
        name: istio
      interval: 5m
  releaseName: istio-base
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: false
  driftDetection:
    mode: enabled
    ignore:
    # ignore Horizontal Pod Autoscaling
    - paths: ["/spec/replicas"]
      target:
        kind: Deployment
  values:
    # set istio "default" revision
    defaultRevision: default
